=== jdominguezm1300/NoSQL/Práctica No.1/Products.dtd
<!ELEMENT Products (Marker*)>
<!ELEMENT Marker (PC*,Laptop*,Printer*)>
<!ATTLIST Marker name CDATA #REQUIRED>
<!ELEMENT PC (Speed,RAM,HardDisk)>
<!ATTLIST PC
  model CDATA #REQUIRED
  price CDATA #REQUIRED> 
<!ELEMENT Laptop (Speed,RAM,HardDisk,Screen)>
<!ATTLIST Laptop
  model CDATA #REQUIRED
  price CDATA #REQUIRED>
<!ELEMENT Printer (Color,Type)>
<!ATTLIST Printer
  model CDATA #REQUIRED
  price CDATA #REQUIRED>
<!ELEMENT Speed (#PCDATA)>
<!ELEMENT RAM (#PCDATA)>
<!ELEMENT HardDisk (#PCDATA)>
<!ELEMENT Screen (#PCDATA)>
<!ELEMENT Color (#PCDATA)>
<!ELEMENT Type (#PCDATA)>

=== jdominguezm1300/NoSQL/Práctica No.1/Products.xml
<!DOCTYPE Products SYSTEM "Products.dtd">
<Products>
  <Marker name="A">
    <PC model="100" price="2114">
      <Speed> 266</Speed>
      <RAM>1024</RAM>
      <HardDisk>250</HardDisk> 
    </PC>
    
     <PC model="1002" price="995">
      <Speed> 2.10</Speed>
      <RAM>512</RAM>
      <HardDisk>250</HardDisk> 
    </PC>
    
    <Laptop model="2004" price="1150">
      <Speed> 2.0</Speed>
      <RAM>512</RAM>
      <HardDisk>60</HardDisk>
      <Screen>13.3</Screen> 
    </Laptop>
    
    <Laptop model="2005" price="2500">
      <Speed> 2.16</Speed>
      <RAM>1024</RAM>
      <HardDisk>120</HardDisk>
      <Screen>17.0</Screen> 
    </Laptop>
  </Marker>
  
  <Marker name="E">
    <PC model="1011" price="959">
        <Speed> 1.56</Speed>
        <RAM>2048</RAM>
        <HardDisk>160</HardDisk> 
    </PC>
    
    <PC model="1012" price="640">
        <Speed> 280</Speed>
        <RAM>1024</RAM>
        <HardDisk>160</HardDisk> 
    </PC>
    
    <Laptop model="2001" price="3675">
      <Speed> 2.0</Speed>
      <RAM>2048</RAM>
      <HardDisk>240</HardDisk>
      <Screen>20.1</Screen> 
    </Laptop>
    
    <Printer model="3002" price="239">
      <Color> false</Color>
      <Type> laser</Type>
    </Printer>
  </Marker>
  
  <Marker name="H">
     <Printer model="3006" price="100">
      <Color> true</Color>
      <Type> ink_jet</Type>
     </Printer>
    
     <Printer model="3007" price="200">
      <Color> true</Color>
      <Type> laser</Type>
     </Printer>
  </Marker>

</Products>
