=== jdominguezm1300/NoSQL/Twitter/Twitter.dtd
<!ELEMENT Twitter (Usuarios*,UsuarioTwitters,Tweets,Tweetears,Retweets,Replies)>
<!ELEMENT Usuarios (Usuario*)>
<!ELEMENT Tweets (Tweet*)>
<!ELEMENT Tweetears (Tweetear*)>
<!ELEMENT Retweets (Retweet*)>
<!ELEMENT Replies (Reply*)>
<!ELEMENT UsuarioTwitters (UsuarioTwitter*)>
<!ELEMENT Usuario (nombrePantalla,localidad,url,fechaCreacion,email)>
<!ATTLIST Usuario usuarioNombre ID #REQUIRED>
<!ELEMENT UsuarioTwitter EMPTY>
<!ATTLIST  UsuarioTwitter 
    usuario IDREF #REQUIRED
    usuarioFollow   IDREF  #REQUIRED>

<!ELEMENT Tweet (text,fechaCreacion)>
<!ATTLIST Tweet 
          tweetId ID #REQUIRED>
<!ELEMENT Retweet EMPTY>
<!ATTLIST  Retweet
    tweetId IDREF #REQUIRED
    usuarioFollow   IDREF #REQUIRED >
<!ELEMENT Reply EMPTY>
<!ATTLIST  Reply
    tweetId IDREF #REQUIRED
    usuarioFollow   IDREF  #REQUIRED >

<!ELEMENT Tweetear EMPTY>
<!ATTLIST   Tweetear
    tweetId IDREF #REQUIRED
    usuario  IDREF #REQUIRED >

<!ELEMENT nombrePantalla (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT fechaCreacion (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT text (#PCDATA)>

=== jdominguezm1300/NoSQL/Twitter/twitter.xml
<?xml version="1.0"?>
<!DOCTYPE Twitter SYSTEM "Twitter.dtd">
<Twitter>
    <Usuarios>
        <Usuario usuarioNombre="Joaks">
            <nombrePantalla> Joaqu√≠n Dominguez</nombrePantalla>
            <localidad> Iztapalapa</localidad>
            <url>www.jw.org</url>
            <fechaCreacion> 12-01-12</fechaCreacion>
            <email> joaks.jdm@gmail.com</email>
        </Usuario>  
        <Usuario usuarioNombre="Jon">
                <nombrePantalla> Yair Carrillo</nombrePantalla>
                <localidad> Iztapalapa</localidad>
                <url>www.jw.org</url>
                <fechaCreacion> 12-02-12</fechaCreacion>
                <email> yair.jdm@gmail.com</email>
        </Usuario>
        <Usuario usuarioNombre="Yair">
                <nombrePantalla> Yair Carrillo</nombrePantalla>
                <localidad> Iztapalapa</localidad>
                <url>www.jw.org</url>
                <fechaCreacion> 12-02-12</fechaCreacion>
                <email> yair.jdm@gmail.com</email>
        </Usuario>

    </Usuarios>
    <UsuarioTwitters>
        <UsuarioTwitter usuario="Joaks" usuarioFollow="Yair"/>
        <UsuarioTwitter usuario="Joaks" usuarioFollow="Jon"/>
        <UsuarioTwitter usuario="Jon" usuarioFollow="Joaks"/>
    </UsuarioTwitters>

    <Tweets>
        <Tweet tweetId="1">
            <text> Hola amigos</text>
            <fechaCreacion> 12-01-12 1:00:00</fechaCreacion>
        </Tweet>

        <Tweet tweetId="2">
                <text> Hola amigos</text>
                <fechaCreacion> 12-01-12 1:00:00</fechaCreacion>
            </Tweet>

    </Tweets>

    <Tweetears>
        <Tweetear tweetId="1" usuario="Joaks"/>
        <Tweetear tweetId="2" usuario="Jon"/>

    </Tweetears>
    <Retweets>
            <Retweet tweetId="1" usuario="Jon"/>
    </Retweets>
    <Replies>
            <Reply tweetId="2" usuario="Joaks"/>
    </Replies>
</Twitter>
